pluginManagement {
    def springBootVersion = providers.gradleProperty("springBootVersion").get()
    def dependencyManagementVersion = providers.gradleProperty("dependencyManagementVersion").get()

    plugins {
        id 'org.springframework.boot' version springBootVersion
        id 'io.spring.dependency-management' version dependencyManagementVersion
    }
}

rootProject.name = 'infra-worker'

include 'worker-stream-example'
include 'worker-webmvc-example'
include 'worker-tool-example'
